/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Duque
 */
public class Propietarios extends javax.swing.JFrame {

    /**
     * Creates new form Propietarios
     */
    public Propietarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonPropiedades = new javax.swing.JButton();
        ButtonPropiedades1 = new javax.swing.JButton();
        ButtonPropiedades2 = new javax.swing.JButton();
        ButtonPropiedades3 = new javax.swing.JButton();
        ButtonPropiedades4 = new javax.swing.JButton();
        ButtonPropiedades5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 110, 47));
        jPanel1.setPreferredSize(new java.awt.Dimension(643, 429));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Propietario");

        ButtonPropiedades.setBackground(new java.awt.Color(135, 159, 41));
        ButtonPropiedades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPropiedades.setText("Profesiones");
        ButtonPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPropiedadesActionPerformed(evt);
            }
        });

        ButtonPropiedades1.setBackground(new java.awt.Color(135, 159, 41));
        ButtonPropiedades1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPropiedades1.setText("Valor de administracion");
        ButtonPropiedades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPropiedades1ActionPerformed(evt);
            }
        });

        ButtonPropiedades2.setBackground(new java.awt.Color(135, 159, 41));
        ButtonPropiedades2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPropiedades2.setText("Saldo");
        ButtonPropiedades2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPropiedades2ActionPerformed(evt);
            }
        });

        ButtonPropiedades3.setBackground(new java.awt.Color(135, 159, 41));
        ButtonPropiedades3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPropiedades3.setText("Factura copropietarios");
        ButtonPropiedades3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPropiedades3ActionPerformed(evt);
            }
        });

        ButtonPropiedades4.setBackground(new java.awt.Color(135, 159, 41));
        ButtonPropiedades4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPropiedades4.setText("Recibo administracion");
        ButtonPropiedades4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPropiedades4ActionPerformed(evt);
            }
        });

        ButtonPropiedades5.setBackground(new java.awt.Color(135, 159, 41));
        ButtonPropiedades5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonPropiedades5.setText("Consultar horas de servicio");
        ButtonPropiedades5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPropiedades5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(268, 268, 268))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPropiedades)
                    .addComponent(ButtonPropiedades1)
                    .addComponent(ButtonPropiedades2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPropiedades4)
                    .addComponent(ButtonPropiedades3)
                    .addComponent(ButtonPropiedades5))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPropiedades3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPropiedades1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPropiedades4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPropiedades2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPropiedades5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPropiedadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPropiedadesActionPerformed

    private void ButtonPropiedades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPropiedades1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPropiedades1ActionPerformed

    private void ButtonPropiedades2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPropiedades2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPropiedades2ActionPerformed

    private void ButtonPropiedades3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPropiedades3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPropiedades3ActionPerformed

    private void ButtonPropiedades4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPropiedades4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPropiedades4ActionPerformed

    private void ButtonPropiedades5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPropiedades5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPropiedades5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Propietarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPropiedades;
    private javax.swing.JButton ButtonPropiedades1;
    private javax.swing.JButton ButtonPropiedades2;
    private javax.swing.JButton ButtonPropiedades3;
    private javax.swing.JButton ButtonPropiedades4;
    private javax.swing.JButton ButtonPropiedades5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
