/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Duque
 */
public class Propiedades extends javax.swing.JFrame {

    /**
     * Creates new form Propiedades
     */
    public Propiedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCrearPropiedades = new javax.swing.JButton();
        ButtonReportePropiedades = new javax.swing.JButton();
        ButtonActualizarPropiedades = new javax.swing.JButton();
        ButtonBorrarPropiedades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 110, 47));
        jPanel1.setPreferredSize(new java.awt.Dimension(643, 429));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Propiedades");

        ButtonCrearPropiedades.setBackground(new java.awt.Color(135, 159, 41));
        ButtonCrearPropiedades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonCrearPropiedades.setText("Crear propiedades");
        ButtonCrearPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearPropiedadesActionPerformed(evt);
            }
        });

        ButtonReportePropiedades.setBackground(new java.awt.Color(135, 159, 41));
        ButtonReportePropiedades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonReportePropiedades.setText("Reporte propiedades");
        ButtonReportePropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReportePropiedadesActionPerformed(evt);
            }
        });

        ButtonActualizarPropiedades.setBackground(new java.awt.Color(135, 159, 41));
        ButtonActualizarPropiedades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonActualizarPropiedades.setText("Actualizar propiedades");
        ButtonActualizarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarPropiedadesActionPerformed(evt);
            }
        });

        ButtonBorrarPropiedades.setBackground(new java.awt.Color(135, 159, 41));
        ButtonBorrarPropiedades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonBorrarPropiedades.setText("Borrar propiedades");
        ButtonBorrarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarPropiedadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonReportePropiedades)
                    .addComponent(ButtonCrearPropiedades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonActualizarPropiedades)
                    .addComponent(ButtonBorrarPropiedades))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCrearPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonActualizarPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonReportePropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBorrarPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCrearPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearPropiedadesActionPerformed
        CrearPropiedades newframe = new CrearPropiedades();

        newframe.setVisible(true);
    }//GEN-LAST:event_ButtonCrearPropiedadesActionPerformed

    private void ButtonReportePropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReportePropiedadesActionPerformed
        JOptionPane.showMessageDialog(this, "PDF generado con la lista de todos los clientes.");
    }//GEN-LAST:event_ButtonReportePropiedadesActionPerformed

    private void ButtonActualizarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarPropiedadesActionPerformed
        ActualizarPropiedades newframe = new ActualizarPropiedades();

        newframe.setVisible(true);
    }//GEN-LAST:event_ButtonActualizarPropiedadesActionPerformed

    private void ButtonBorrarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarPropiedadesActionPerformed
        BorrarPropiedades newframe = new BorrarPropiedades();

        newframe.setVisible(true);
    }//GEN-LAST:event_ButtonBorrarPropiedadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Propiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Propiedades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizarPropiedades;
    private javax.swing.JButton ButtonBorrarPropiedades;
    private javax.swing.JButton ButtonCrearPropiedades;
    private javax.swing.JButton ButtonReportePropiedades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
